// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"crud-go-server/internal/app"
	"crud-go-server/internal/pkg/api"
	"crud-go-server/internal/pkg/db"
	"crud-go-server/internal/pkg/repo"
	"crud-go-server/internal/setting"
)

// Injectors from wire.go:

func initGoApp() (app.App, error) {
	config := setting.NewServerConfig()
	gormDB, err := db.NewMySqlSession(config)
	if err != nil {
		return nil, err
	}
	studentRepo := repo.NewStudentRepo(gormDB)
	studentHandler := api.NewStudentHandler(studentRepo)
	moduleRepo := repo.NewModuleRepo(gormDB)
	moduleHandler := api.NewModuleHandler(moduleRepo)
	markRepo := repo.NewMarkRepo(gormDB)
	markHandler := api.NewMarkHandler(markRepo)
	httpServer := app.NewHttpServer(studentHandler, moduleHandler, markHandler)
	appApp := app.NewApp(httpServer)
	return appApp, nil
}
